from NLP.ExecutionObject import ExecutionObject as e_object
import PM.pm as pm
from Enums.reply_enum import ReplyType
from Enums.execution_enum import ExecutionState as Execution
import NLP.execution as execution

objects =  [e_object("Alpha",
                     "/alpha",
                     "Does the alpha miner on the current log.", 
                     pm.do_alpha_miner, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),
            e_object("Conformance",
                     "", 
                     "", 
                     "", 
                     "Okay, what kind of conformance check do you have in mind? \n Currently supported checks are: Fitness, Precision and a Complete conformance check covering both fitness, precision and simplicity checks", 
                     ReplyType.text, 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("Conformance_complete_follow",
                     "", 
                     "", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Conformance_fitness_follow",
                     "", 
                     "", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Conformance_precision_follow",
                     "", 
                     "", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Conformance_complete",
                     "/conformance_complete", 
                     "Does complete conformance checking on the current log and model", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Conformance_fitness",
                     "/conformance_fitness", 
                     "Does fitness conformance checking on the current log and model", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Conformance_precision",
                     "/conformance_precision",
                     "Does precision conformance checking on the current log and model", 
                     pm.do_conformance, 
                     Execution.Both, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Current_log",
                     "/currentlog",
                     "Shows the current log of this chat",
                     "GetCurrentLog()",
                     Execution.Nothing,
                     ReplyType.text,
                     False,
                     False),
            e_object("Current_model",
                     "/currentmodel",
                     "Shows the current model of this chat",
                     "GetCurrentModel()",
                     Execution.Nothing,
                     ReplyType.text,
                     False,
                     False),
            e_object("DescribeLog",
                     "/describelog", 
                     "Describes the current log", 
                     pm.log_desciption, 
                     Execution.Log, 
                     ReplyType.multi, 
                     True, 
                     False),
            e_object("DFG",
                     "", 
                     "", 
                     "What kind of directly follows graph would you like me to do? Resource or performance?", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("DFG_resource_follow",
                     "", 
                     "", 
                     pm.do_dfg, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),
            e_object("DFG_performance_follow",
                     "", 
                     "", 
                     pm.do_dfg, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),
            e_object("DFG_performance",
                     "/dfg_performance", 
                     "Makes a directly follows graph for performance", 
                     pm.do_dfg, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),
            e_object("DFG_resource",
                     "/dfg_resource", 
                     "Makes a directly follows graphs for resouces", 
                     pm.do_dfg, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),  
            e_object("Discovery",
                     "",
                     "", 
                     "Okay, what kind of discovery would you like to perform? \n Currently I support: dfg, alpha miner, inductive miner, description of the log, dotted charts and precedence matrix", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Dottedchart",
                     "", 
                     "", 
                     "What kind of dotted chart would you like me to do? Relative or absolute?", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Dottedchart_absolute_follow",
                     "", 
                     "", 
                     "pass", 
                     Execution.Log, 
                     "", 
                     True, 
                     False),
            e_object("Dottedchart_relative_follow",
                     "",
                     "", 
                     "pass", 
                     Execution.Log, 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("Dottedchart_absolute",
                     "/dottedchartabsolute",
                     "Creates an absolute dotted chart for the current log", 
                     "!", 
                     Execution.Log, 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("Dottedchart_relative",
                     "/dottedchartrelative", 
                     "Creates a relative dotted chart for the current log", 
                     "pass", 
                     Execution.Log, 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("Fine",
                     "", 
                     "That's nice to hear!", 
                     "", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Help",
                     "/help", 
                     "Shows the help menu", 
                     execution.get_help_text, 
                     Execution.Nothing, 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("HowAreYou",
                     "", 
                     "", 
                     "I am fine and you?", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Inductive",
                     "/inductive", 
                     "Does the inductive miner on the current log", 
                     pm.do_inductive_miner, 
                     Execution.Log, 
                     ReplyType.photo, 
                     True, 
                     False),
            e_object("Mining",
                     "", 
                     "", 
                     "pass", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("No",
                     "", 
                     "", 
                     "pass", 
                     "", 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("PrecedenceMatrix",
                     "/precedencematrix", 
                     "Creates a precedence matrix for the current log", 
                     "pass", 
                     Execution.Log, 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED
            e_object("Sad",
                     "", 
                     "", 
                     "I'm sorry to hear that. What's the problem?", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Show_resources",
                     "/resources", 
                     "Shows the current resources", 
                     "pass", 
                     Execution.Log, 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED SHOW MIMIC (SHOWRESOURCES FROM PMBOT)
            e_object("Welcome",
                     "", 
                     "", 
                     "Hi user! nice to meet you!", 
                     "", 
                     ReplyType.text, 
                     True, 
                     False),
            e_object("Yes",
                     "", 
                     "", 
                     "pass", 
                     "", 
                     "", 
                     True, 
                     False), #TO BE IMPLEMENTED

            e_object("List",
                     "/list", 
                     "Lists the files currently available in this chat", 
                     "list files", 
                     Execution.Nothing, 
                     ReplyType.text, 
                     True, 
                     False)]             #TO BE IMPLEMENTED
